on:
  pull_request:
    types: [edited, opened, reopened]

permissions: write-all

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Apply dynamic template changes
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"

      - uses: luigibertaco/dynamic-template-action@1.0.0
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          customInput: 
            today: ${{ steps.date.outputs.date }}
            now: ${{ steps.date.outputs.date }}