name: PR update

on:
  pull_request:
    types: [opened]

jobs:
  stale:

    runs-on: ubuntu-latest
    steps:
      - name: Check Branch
        id: check-branch
        run: |
          if [[ ${{ github.head_ref }} =~ ^JIRA-.*$ ]]; then
              echo "Good name!"
              exit 0
          else
              echo "Bad name!"
              exit 1   
          fi