name: PR update

on:
  pull_request:
    types: [opened]

jobs:
  stale:

    runs-on: ubuntu-latest
    steps:
      - name: Check Branch
        id: check-branch
        run: |
          if [[ ${{ github.event.pull_request.title }} =~ ^.*JIRA-.*$ ]]; then
              echo ::set-output name=match::true
          fi
      - name: Generate Link
        if: steps.check-branch.outputs.match == 'true'
        run: |
              echo "Good name!"
              exit 0